name: Build and Package PII Scanner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --uac-admin --add-data ".env.example;." --add-data "pii_scanner.xml;." --hidden-import=sqlite3 pii_scanner.py

      - name: Install NSIS
        run: |
          choco install nsis -y

      - name: Create NSIS installer
        run: |
          makensis pii_scanner_installer.nsi

      - name: Upload installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: PII_Scanner_Installer
          path: PII_Scanner_Installer.exe
