name: Build and Package PII Scanner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install "protobuf<=3.20.0" --force-reinstall

      - name: Download GLiNER models
        run: |
          python -c "import os; os.environ['PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION'] = 'python'; from gliner import GLiNER; GLiNER.from_pretrained('urchade/gliner_multi_pii-v1'); GLiNER.from_pretrained('urchade/gliner_multiv2.1')"

      - name: Copy models to build directory
        run: |
          mkdir -p dist/models
          xcopy /E /I "%USERPROFILE%\.cache\huggingface" dist\models

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --uac-admin --add-data ".env.example;." --add-data "pii_scanner.xml;." --add-data "dist/models;models" --hidden-import=sqlite3 --hidden-import=openpyxl pii_scanner.py

      - name: Install NSIS
        run: |
          choco install nsis -y

      - name: Create NSIS installer
        run: |
          makensis pii_scanner_installer.nsi

      - name: Upload installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: PII_Scanner_Installer
          path: PII_Scanner_Installer.exe
